### PR TITLE
Cardioid demo

### PR DESCRIPTION
**Pull request by bowguy**
Additional demo to create Cardioid from tangent line segments along evenly spaced points along a circle

### CODE REVIEW

**Comment by dr-jts** [comment]
Nice!  

I think better to have a more general dir name though. Maybe put it in the `opart` dir, or perhaps a `math` dir?

**Comment by bowguy** [comment]
Sounds good to me!
I am playing with this because it is fun and also I have a computerized
embroidery machine.  The data flow is:
PostGIS -> SVG -> Windows Meta File via Inkscape - > .pem embroidery format
-> embroidery.
Lots of other ideas at 3blue1brown YouTube Channel

**Comment by bowguy** [comment]
Pick a directory for this stuff and I will resubmitt the pull request if you want

**Comment by dr-jts** [comment]
> Pick a directory for this stuff and I will resubmitt the pull request if you want

Great.  Put it in `opart`.

**Comment by dr-jts** [comment]
Are you abandoning this?  If you want to change directory just do that and repush to this branch.

Oh never mind - I see the new PR.

**Pull request closed without merging**
