### PR TITLE
Update pg-svg-lib.sql

### PR DESCRIPTION
**Pull request by CM-FOGS**
We need to clarify a possible syntax error in code line #531

### CODE REVIEW

**Comment by CM-FOGS** [comment]
We need to clarify a possible syntax error in code line #531

**Comment by dr-jts** [comment]
It looks like PL/pgSQL is insensitive to the keyword following `END`, since using `END IF` does not cause an error.   But to ensure correctness this should be `END CASE`.

**Comment by CM-FOGS** [comment]
I noticed this because the error handler in version PostgreSQL 12.4, compiled by Visual C++ build 1914, 64-bit didn't create this function, now it's fine :-)....

**Comment by CM-FOGS** [comment]
I noticed this because I was trying to create these functions using PGAdmin in the version PostgreSQL 12.4, compiled by Visual C++ build 1914, 64-bit and couldn't create this particular function, now it's in order :-)....

**Pull request closed without merging**
